Fix responsiveness of main content component
Software-Lifecycle-Consultants/susdevos pull request #43
Opened 2024-03-12 07:04 UTC by yohan9878

2024-03-13 06:20 UTC, yohan9878 commented
Resolved Conflicts after merging feature-main-content into feature-landing-page

2024-03-13 06:35 UTC, iamarasekera approved these changes

2024-03-15 08:32 UTC, iamarasekera approved these changes

2024-03-18 06:32 UTC, iamarasekera requested changes

2024-03-18 06:32 UTC, iamarasekera commented on components/MainContent/index.tsx
> +        {/* Get SusDev OS Form */}
Remove the commented code.

2024-03-18 06:44 UTC, iamarasekera approved these changes

2024-03-18 06:44 UTC, merged